# Generated by Django 2.0.8 on 2019-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, db_column='Book_Name', max_length=50, null=True)),
                ('book_code', models.DecimalField(db_column='Book_Code', decimal_places=0, max_digits=2)),
                ('active', models.TextField(blank=True, db_column='Active', null=True)),
            ],
        ),
    ]
